name: eux-slett-usendte-rinasaker-slett-naisjob
schedule: "0 1 * * *"

slettprosess: slett

application:
  eux-slett-usendte-rinasaker:
    name: eux-slett-usendte-rinasaker
    namespace: eessibasis
    endpoint: http://eux-slett-usendte-rinasaker
    scope: api://prod-gcp.eessibasis.eux-slett-usendte-rinasaker/.default
